version: "3.9"

services:
  web:
    image: ghcr.io/bugsquasher-4253/crm:${IMAGE_TAG:-prod}
    build: .
    container_name: crefio_web
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    env_file: .env
    environment:
      - MEDIA_ROOT=/app/attendance_project/media
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - media_data:/app/attendance_project/media

volumes:
  media_data:
