# Generated by Django 6.0.5 on 2026-05-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_leaverequest_supportticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="aadhaar_card",
            field=models.FileField(blank=True, null=True, upload_to="documents/aadhaar/"),
        ),
        migrations.AddField(
            model_name="employee",
            name="pan_card",
            field=models.FileField(blank=True, null=True, upload_to="documents/pan/"),
        ),
    ]
