# Generated by Django 6.0.5 on 2026-05-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_attendancecorrectionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="has_seen_document_reminder",
            field=models.BooleanField(default=False),
        ),
    ]
