# Generated by Django 6.0.5 on 2026-05-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_employee_has_seen_document_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="salaryrecord",
            name="absent_days",
            field=models.IntegerField(default=0),
        ),
    ]
