# Generated by Django 6.0.5 on 2026-05-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_salaryrecord_absent_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="salaryrecord",
            name="half_days",
            field=models.IntegerField(default=0),
        ),
    ]
