# Generated by Django 6.0.5 on 2026-05-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_add_half_days_to_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("technical", "Technical Issue"),
                    ("hr", "HR"),
                    ("payroll", "Payroll"),
                    ("leave", "Leave"),
                    ("general", "General Query"),
                    ("other", "Other"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("waiting", "Waiting for Response"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
