
# Generated by Django 6.0.5 on 2026-05-31 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_add_ticket_category_priority_waiting"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeSalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "effective_from",
                    models.DateField(
                        help_text="First day of the month this salary takes effect"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="e.g. Annual increment, promotion"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_structures",
                        to="attendance.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from"],
                "unique_together": {("employee", "effective_from")},
            },
        ),
    ]
