# Generated by Django 6.0.5 on 2026-05-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_add_employee_salary_structure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeesalarystructure",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
