# Generated by Django 6.0.5 on 2026-07-07 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0012_add_reimbursement"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="break_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="net_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.CreateModel(
            name="AttendanceBreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pause_start", models.TimeField()),
                ("pause_end", models.TimeField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="attendance.attendancerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["pause_start"],
            },
        ),
    ]
